server:
 port: ${PORT:8585}
 servlet-path: /employee-service

#spring:
#  datasource:
#      initialize: true #Only on dev
#      url: jdbc:h2:~/prestige;DB_CLOSE_ON_EXIT=FALSE
#      driverClassName: org.h2.Driver
#      username: sa
#      password:
#    jpa:
#      show-sql: true
#      database-platform: org.hibernate.dialect.H2Dialect
#    h2:
#      console:
#        enabled: true
#        path: /h2